kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: opensearch
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: db
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
