apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | default "urnr" }}
  name: front-service
  labels:
    app: front-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: ngnix-exporter
      protocol: TCP
      port: 9113
      targetPort: 9113
  selector:
    app: front

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | default "urnr" }}
  name: back-service
  labels:
    app: back-service
spec:
  type: LoadBalancer
  ports:
    - name: back
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: spring-actuator
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app: back
